version: "3.8"

services:
#================================
#      POSTGRES
#================================
  farm_db:
    image: postgres:14-alpine
    container_name: farm_db
    restart: always
    volumes:
      - farm_db:/var/lib/postgresql/data/
    env_file:
      - ./src/.env

#================================
#       WEB APPLICATION
#================================
  farm_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: farm_app
    restart: on-failure
    container_name: farm_app
    env_file:
        - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - farm_db
    volumes:
      - ./src:/src
      - farm_media:/src/media
      - farm_static:/src/static

#================================
#       NGINX
#================================
  nginx:
    image: nginx:1.21.6
    container_name: movies_nginx
    restart: always
    volumes:
      - farm_static:/src/static
      - farm_media:/src/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/:/etc/nginx/conf.d:ro
    depends_on:
      - farm_app
    ports:
      - "80:80"

volumes:
  farm_db: {}
  farm_media: {}
  farm_static: {}
