# Generated by Django 4.1.3 on 2022-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Максимальная длина названия 60 символов.', max_length=60, verbose_name='Название компании')),
                ('phone_number', models.CharField(help_text='Максимальная длина 120 символов', max_length=120, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, help_text='Максимальная длина 120 символов', max_length=120, null=True, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, help_text='Максимальная длина 120 символов', max_length=120, null=True, verbose_name='Telegram')),
                ('email', models.EmailField(help_text='Электронная почта компании', max_length=254, verbose_name='e-Mail')),
                ('region', models.CharField(help_text='Используется для отображения на странице "Как нас найти?"', max_length=120, verbose_name='Область')),
                ('city_type', models.CharField(choices=[('city', 'Город'), ('village', 'Деревня'), ('township', 'Поселок')], default='city', help_text='Выбрать из предложенных', max_length=15, verbose_name='Тип поселения')),
                ('city', models.CharField(help_text='Название города, максимальная длина 120 символов', max_length=120, verbose_name='Город')),
                ('street', models.CharField(help_text='Адрес, максимальная длина 500"', max_length=500, verbose_name='Адрес')),
                ('index', models.CharField(help_text='Индекс, максимальная длина 10"', max_length=10, verbose_name='Индекс')),
                ('head_title', models.CharField(help_text='Заглавие основной страницы, максимальная длина 30 символов', max_length=30, verbose_name='Шапка, заглавие')),
                ('head_description', models.TextField(help_text='Описание основной страницы, максимальная длина 300 символов', max_length=300, verbose_name='Шапка, описание')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
