# Generated by Django 4.1.3 on 2022-11-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_create_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(help_text='Название города, максимальная длина 120 символов.', max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='city_type',
            field=models.CharField(choices=[('city', 'Город'), ('village', 'Деревня'), ('township', 'Поселок')], default='city', help_text='Выбрать из предложенных.', max_length=15, verbose_name='Тип поселения'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(help_text='Электронная почта компании.', max_length=254, verbose_name='e-Mail'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='head_description',
            field=models.TextField(help_text='Описание основной страницы, максимальная длина 300 символов.', max_length=300, verbose_name='Шапка, описание'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='head_title',
            field=models.CharField(help_text='Заглавие основной страницы, максимальная длина 30 символов.', max_length=30, verbose_name='Шапка, заглавие'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='index',
            field=models.CharField(help_text='Индекс, максимальная длина 10.', max_length=10, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_number',
            field=models.CharField(help_text='Максимальная длина 120 символов.', max_length=120, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='region',
            field=models.CharField(help_text='Максимальная длина 120 символов.', max_length=120, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='street',
            field=models.CharField(help_text='Адрес, максимальная длина 500.', max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, help_text='Максимальная длина 120 символов.', max_length=120, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Максимальная длина 120 символов.', max_length=120, null=True, verbose_name='WhatsApp'),
        ),
    ]
